---
- name: deploy server on digital ocean
- digital_ocean:
  state: present
  command: droplet
  name: webserver
  api_token: token
  size_id: 512mb
  region_id: nyc3
  image_id: ubuntu-16.04-x64
 
 register: my_droplet

- debug: msg="ID is {{ my_droplet.droplet.id }}"
- debug: msg="IP is {{ my_droplet.droplet.ip_address }}"

