---
- name: Install nginx, openvpn, git 
  hosts: webservers
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: install python2
      raw: apt-get -y install python2.7 python-simplejson

  roles:
   - common
   - nginx
   - ufw
   - openvpn
   - beats
